<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\Hosts\Consumers\SmartLedger.Common.Host.Consumers.csproj" />
    <ProjectReference Include="..\..\..\..\Common\Infrastructures\DataAccess\SmartLedger.Common.Infrastructures.DataAccess.csproj" />
    <ProjectReference Include="..\..\..\Webhooks\Applications\AppServices\SmartLedger.Modules.Webhooks.Applications.AppServices.csproj" />
    <ProjectReference Include="..\..\..\Webhooks\Infrastructures\DataAccess\SmartLedger.Modules.Webhooks.Infrastructures.DataAccess.csproj" />
    <ProjectReference Include="..\..\Applications\AppServices\SmartLedger.Modules.Notifications.Applications.AppServices.csproj" />
    <ProjectReference Include="..\..\Contracts\SmartLedger.Modules.Notifications.Contracts.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\launchSettings.json">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
