<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IntermodularEvents\**" />
    <EmbeddedResource Remove="IntermodularEvents\**" />
    <None Remove="IntermodularEvents\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Contracts\SmartLedger.Common.Contracts.csproj" />
  </ItemGroup>

</Project>
