services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: smartledger-db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: smartledger_db
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartledger_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smartledger-network

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: smartledger-pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartledger.com
      PGADMIN_DEFAULT_PASSWORD: adminp4ss
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    user: "5050:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - smartledger-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartledger-rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmqp4ss
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - smartledger-network

  # Redis
  redis:
    container_name: smartledger-redis
    image: redis:7.2-alpine
    restart: on-failure
    command: >
      --requirepass p4ssword
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - smartledger-network

  # OpenSearch
  opensearch:
    container_name: smartledger-opensearch
    image: opensearchproject/opensearch:2.19.0
    restart: on-failure
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Op3nS3archP@ss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
      timeout: 5s
    volumes:
      - opensearch-logs:/usr/share/opensearch/data
    networks:
      - smartledger-network

  # OpenSearch Dashboard
  opensearch-dashboard:
    container_name: smartledger-opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2.19.0
    restart: on-failure
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - smartledger-network

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: smartledger-otel-collector
    restart: on-failure
    volumes:
      - ./config/otel-collector/config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
    command: ["--config", "/etc/otelcol-contrib/config.yaml"]
    depends_on:
      - prometheus
      - loki
      - jaeger-all-in-one
    networks:
      - smartledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: smartledger-prometheus
    restart: on-failure
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
    networks:
      - smartledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Loki
  loki:
    image: grafana/loki:latest
    container_name: smartledger-loki
    restart: on-failure
    ports:
      - '3100:3100'
    volumes:
    - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
    - loki-data:/loki
    networks:
      - smartledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: smartledger-jaeger
    restart: on-failure
    ports:
      - "16686:16686"   # Web UI
      - "14268:14268"   # HTTP collector
      - "14250:14250"   # GRPC collector
      - "6831:6831/udp" # Jaeger Agent (UDP)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - smartledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: smartledger-grafana
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - jaeger-all-in-one
     
    networks:
      - smartledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  pgadmin-data:  
  rabbitmq-data: 
  redis-data:
  opensearch-logs:
  prometheus-data:
  loki-data:
  grafana-data:

networks:
  smartledger-network:
    driver: bridge