services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: smartledger-db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: smartledger_db
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartledger_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smartledger-network

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: smartledger-pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartledger.com
      PGADMIN_DEFAULT_PASSWORD: adminp4ss
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    user: "5050:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - smartledger-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: smartledger-keycloak
    restart: on-failure
    command: >
      start-dev
      --import-realm
      --log-level=info
    user: root
    environment:
      KC_FEATUES: preview
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: p4ssw0rd
      KC_HOSTNAME: localhost
      KC_MATRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminp4ss
    ports:
      - 8090:8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import
      - ./config/keycloak/providers:/opt/keycloak/providers
      - keycloak_logs:/opt/keycloak/data/log/
    networks:
      - smartledger-network
  
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartledger-rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmqp4ss
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - smartledger-network

  # Redis
  redis:
    container_name: smartledger-redis
    image: redis:7.2-alpine
    restart: on-failure
    command: >
      --requirepass p4ssword
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - smartledger-network

  # OpenSearch
  opensearch:
    container_name: smartledger-opensearch
    image: opensearchproject/opensearch:2.19.0
    restart: on-failure
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Op3nS3archP@ss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
      timeout: 5s
    volumes:
      - opensearch-logs:/usr/share/opensearch/data
    networks:
      - smartledger-network

  # OpenSearch Dashboard
  opensearch-dashboard:
    container_name: smartledger-opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2.19.0
    restart: on-failure
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - smartledger-network

volumes:
  postgres-data:
  pgadmin-data:  
  rabbitmq-data: 
  redis-data:
  opensearch-logs:
  keycloak_logs:

networks:
  smartledger-network:
    driver: bridge