<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Handlers\Contexts\Accounts\Queries\" />
    <Folder Include="Handlers\Contexts\Transactions\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Applications\SmartLedger.Common.Applications.csproj" />
    <ProjectReference Include="..\Domain\SmartLedger.Modules.Transactions.Domain.csproj" />
    <ProjectReference Include="..\Events\SmartLedger.Modules.Transactions.Events.csproj" />
    <ProjectReference Include="..\Infrastructure\SmartLedger.Modules.Transactions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
