<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contexts\Read\Configurations\" />
    <Folder Include="Contexts\Read\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Infrastructure\SmartLedger.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Domain\SmartLedger.Modules.Transactions.Domain.csproj" />
  </ItemGroup>

</Project>
