// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLedger.Modules.Transactions.Infrastructure.Contexts.Read;

#nullable disable

namespace SmartLedger.Modules.Transactions.Hosts.Migrations.Migrations.ReadDbContext
{
    [DbContext(typeof(TransactionsReadDbContext))]
    partial class TransactionsReadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("read")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLedger.Modules.Transactions.Infrastructure.Contexts.Read.Models.AccountReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_accounts_userid");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_accounts_userid_createdat");

                    b.ToTable("Accounts", "read");
                });

            modelBuilder.Entity("SmartLedger.Modules.Transactions.Infrastructure.Contexts.Read.Models.TransactionReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_transactions_accountid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_transactions_userid");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_transactions_userid_createdat");

                    b.HasIndex("AccountId", "Category", "CreatedAt")
                        .HasDatabaseName("idx_transactions_accountid_category_createdat");

                    b.HasIndex("UserId", "Type", "CreatedAt")
                        .HasDatabaseName("idx_transactions_userid_type_createdat");

                    b.ToTable("Transactions", "read");
                });
#pragma warning restore 612, 618
        }
    }
}
