<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>00c28157-e9a5-4f11-b328-97cd719c3082</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Cqrs\SmartLedger.Common.Cqrs.csproj" />
    <ProjectReference Include="..\..\Common\Infrastructure\SmartLedger.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Budgets\Applications\Handlers\SmartLedger.Modules.Budgets.Applications.Handlers.csproj" />
    <ProjectReference Include="..\..\Modules\Budgets\Infrastructure\SmartLedger.Modules.Budgets.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Transactions\Applications\AppServices\SmartLedger.Modules.Transactions.Applications.AppServices.csproj" />
    <ProjectReference Include="..\..\Modules\Transactions\Applications\Handlers\SmartLedger.Modules.Transactions.Applications.Handlers.csproj" />
    <ProjectReference Include="..\..\Modules\Transactions\Contracts\SmartLedger.Modules.Transactions.Contracts.csproj" />
  </ItemGroup>

</Project>
