// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartLedger.Modules.Budgets.Infrastructure.Contexts.Write;

#nullable disable

namespace SmartLedger.Modules.Budgets.Hosts.Migrations.Migrations.WriteDbContext
{
    [DbContext(typeof(BudgetsWriteDbContext))]
    partial class BudgetsWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("write")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartLedger.Modules.Budgets.Domain.Aggregates.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Budgets", "write");
                });

            modelBuilder.Entity("SmartLedger.Modules.Budgets.Domain.Entities.BudgetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetItems", "write");
                });

            modelBuilder.Entity("SmartLedger.Modules.Budgets.Domain.Aggregates.Budget", b =>
                {
                    b.OwnsOne("SmartLedger.Modules.Budgets.Domain.ValueObjects.BudgetName", "Name", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.HasKey("BudgetId");

                            b1.ToTable("Budgets", "write");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");
                        });

                    b.OwnsOne("SmartLedger.Modules.Budgets.Domain.ValueObjects.BudgetPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDate")
                                .HasDefaultValueSql("now()");

                            b1.Property<DateTime>("StartDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartDate")
                                .HasDefaultValueSql("now()");

                            b1.HasKey("BudgetId");

                            b1.ToTable("Budgets", "write");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLedger.Modules.Budgets.Domain.Entities.BudgetItem", b =>
                {
                    b.HasOne("SmartLedger.Modules.Budgets.Domain.Aggregates.Budget", null)
                        .WithMany("Items")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartLedger.Modules.Budgets.Domain.ValueObjects.BudgetItemLimit", "Limit", b1 =>
                        {
                            b1.Property<Guid>("BudgetItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Limit");

                            b1.HasKey("BudgetItemId");

                            b1.ToTable("BudgetItems", "write");

                            b1.WithOwner()
                                .HasForeignKey("BudgetItemId");
                        });

                    b.OwnsOne("SmartLedger.Modules.Transactions.Domain.ValueObjects.Money", "SpentAmount", b1 =>
                        {
                            b1.Property<Guid>("BudgetItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SpentAmount");

                            b1.HasKey("BudgetItemId");

                            b1.ToTable("BudgetItems", "write");

                            b1.WithOwner()
                                .HasForeignKey("BudgetItemId");
                        });

                    b.Navigation("Limit")
                        .IsRequired();

                    b.Navigation("SpentAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLedger.Modules.Budgets.Domain.Aggregates.Budget", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
