<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contexts\Users\Commands\" />
    <Folder Include="Contexts\Users\Events\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\Applications\Handlers\SmartLedger.Common.Applications.Handlers.csproj" />
    <ProjectReference Include="..\AppServices\SmartLedger.Modules.Security.Applications.AppServices.csproj" />
  </ItemGroup>

</Project>
